
#ifndef EXECUTION_VIS_H
#define EXECUTION_VIS_H

#include "execution_classes.h"

namespace EXECUTION
{
namespace visualization
{

/**
 * @brief visualize the grid map
 */
void visWorld(World* world,ros::Publisher* world_vis_pub);

/**
 * @brief visualize the plane of the nodes along the path generated by PF-RRT*
 */
void visSurf(const std::vector<Node*> &solution,ros::Publisher* surf_vis_pub);

/**
 * @brief visualize the start point and the end point of PF-RRT*
 */
void visOriginAndGoal(const std::vector<Node*> &pts,ros::Publisher* origin_and_goal_vis_pub);

/**
 * @brief visualize the path generated by PF-RRT*
 */
void visPath(const std::vector<Node*> &solution,ros::Publisher* path_vis_pub);

/**
 * @brief visualize the tree of PF-RRT*
 */
void visTree(const std::vector<Node*> &tree,ros::Publisher* tree_vis_pub);
}

}
#endif